# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import post_pb2 as post__pb2

GRPC_GENERATED_VERSION = '1.73.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in post_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PostsServiceStub(object):
    """---------------------------------------------------------------------------
    Service
    ---------------------------------------------------------------------------

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreatePost = channel.unary_unary(
                '/posts.PostsService/CreatePost',
                request_serializer=post__pb2.PostCreateRequest.SerializeToString,
                response_deserializer=post__pb2.PostResponse.FromString,
                _registered_method=True)
        self.GetPost = channel.unary_unary(
                '/posts.PostsService/GetPost',
                request_serializer=post__pb2.PostRequest.SerializeToString,
                response_deserializer=post__pb2.PostResponse.FromString,
                _registered_method=True)
        self.UpdatePost = channel.unary_unary(
                '/posts.PostsService/UpdatePost',
                request_serializer=post__pb2.PostUpdateRequest.SerializeToString,
                response_deserializer=post__pb2.PostResponse.FromString,
                _registered_method=True)
        self.DeletePost = channel.unary_unary(
                '/posts.PostsService/DeletePost',
                request_serializer=post__pb2.PostRequest.SerializeToString,
                response_deserializer=post__pb2.GenericResponse.FromString,
                _registered_method=True)
        self.GetPostsByUser = channel.unary_unary(
                '/posts.PostsService/GetPostsByUser',
                request_serializer=post__pb2.GetPostsByUserRequest.SerializeToString,
                response_deserializer=post__pb2.PostListResponse.FromString,
                _registered_method=True)
        self.GetMyPosts = channel.unary_unary(
                '/posts.PostsService/GetMyPosts',
                request_serializer=post__pb2.GetMyPostsRequest.SerializeToString,
                response_deserializer=post__pb2.PostListResponse.FromString,
                _registered_method=True)
        self.GetPublicPosts = channel.unary_unary(
                '/posts.PostsService/GetPublicPosts',
                request_serializer=post__pb2.GetPublicPostsRequest.SerializeToString,
                response_deserializer=post__pb2.PostListResponse.FromString,
                _registered_method=True)
        self.GetPropertyPosts = channel.unary_unary(
                '/posts.PostsService/GetPropertyPosts',
                request_serializer=post__pb2.GetPropertyPostsRequest.SerializeToString,
                response_deserializer=post__pb2.PostListResponse.FromString,
                _registered_method=True)
        self.GetBuilderPosts = channel.unary_unary(
                '/posts.PostsService/GetBuilderPosts',
                request_serializer=post__pb2.GetBuilderPostsRequest.SerializeToString,
                response_deserializer=post__pb2.PostListResponse.FromString,
                _registered_method=True)
        self.SearchPosts = channel.unary_unary(
                '/posts.PostsService/SearchPosts',
                request_serializer=post__pb2.SearchPostsRequest.SerializeToString,
                response_deserializer=post__pb2.PostListResponse.FromString,
                _registered_method=True)
        self.TrendingPosts = channel.unary_unary(
                '/posts.PostsService/TrendingPosts',
                request_serializer=post__pb2.TrendingPostsRequest.SerializeToString,
                response_deserializer=post__pb2.PostListResponse.FromString,
                _registered_method=True)
        self.PinPost = channel.unary_unary(
                '/posts.PostsService/PinPost',
                request_serializer=post__pb2.PostOwnerRequest.SerializeToString,
                response_deserializer=post__pb2.PostResponse.FromString,
                _registered_method=True)
        self.UnpinPost = channel.unary_unary(
                '/posts.PostsService/UnpinPost',
                request_serializer=post__pb2.PostOwnerRequest.SerializeToString,
                response_deserializer=post__pb2.PostResponse.FromString,
                _registered_method=True)
        self.ArchivePost = channel.unary_unary(
                '/posts.PostsService/ArchivePost',
                request_serializer=post__pb2.PostOwnerRequest.SerializeToString,
                response_deserializer=post__pb2.PostResponse.FromString,
                _registered_method=True)
        self.RestoreArchivedPost = channel.unary_unary(
                '/posts.PostsService/RestoreArchivedPost',
                request_serializer=post__pb2.PostOwnerRequest.SerializeToString,
                response_deserializer=post__pb2.PostResponse.FromString,
                _registered_method=True)
        self.AddPostMedia = channel.unary_unary(
                '/posts.PostsService/AddPostMedia',
                request_serializer=post__pb2.PostMediaRequest.SerializeToString,
                response_deserializer=post__pb2.PostResponse.FromString,
                _registered_method=True)
        self.DeletePostMedia = channel.unary_unary(
                '/posts.PostsService/DeletePostMedia',
                request_serializer=post__pb2.MediaIdRequest.SerializeToString,
                response_deserializer=post__pb2.GenericResponse.FromString,
                _registered_method=True)
        self.LikePost = channel.unary_unary(
                '/posts.PostsService/LikePost',
                request_serializer=post__pb2.LikeRequest.SerializeToString,
                response_deserializer=post__pb2.PostResponse.FromString,
                _registered_method=True)
        self.UnlikePost = channel.unary_unary(
                '/posts.PostsService/UnlikePost',
                request_serializer=post__pb2.LikeRequest.SerializeToString,
                response_deserializer=post__pb2.PostResponse.FromString,
                _registered_method=True)
        self.GetPostLikes = channel.unary_unary(
                '/posts.PostsService/GetPostLikes',
                request_serializer=post__pb2.GetPostLikesRequest.SerializeToString,
                response_deserializer=post__pb2.PostLikeListResponse.FromString,
                _registered_method=True)
        self.CheckLikeStatus = channel.unary_unary(
                '/posts.PostsService/CheckLikeStatus',
                request_serializer=post__pb2.CheckLikeStatusRequest.SerializeToString,
                response_deserializer=post__pb2.CheckLikeStatusResponse.FromString,
                _registered_method=True)
        self.CreateComment = channel.unary_unary(
                '/posts.PostsService/CreateComment',
                request_serializer=post__pb2.CommentCreateRequest.SerializeToString,
                response_deserializer=post__pb2.CommentResponse.FromString,
                _registered_method=True)
        self.UpdateComment = channel.unary_unary(
                '/posts.PostsService/UpdateComment',
                request_serializer=post__pb2.CommentUpdateRequest.SerializeToString,
                response_deserializer=post__pb2.CommentResponse.FromString,
                _registered_method=True)
        self.DeleteComment = channel.unary_unary(
                '/posts.PostsService/DeleteComment',
                request_serializer=post__pb2.CommentRequest.SerializeToString,
                response_deserializer=post__pb2.GenericResponse.FromString,
                _registered_method=True)
        self.GetComments = channel.unary_unary(
                '/posts.PostsService/GetComments',
                request_serializer=post__pb2.GetCommentsRequest.SerializeToString,
                response_deserializer=post__pb2.CommentListResponse.FromString,
                _registered_method=True)
        self.GetComment = channel.unary_unary(
                '/posts.PostsService/GetComment',
                request_serializer=post__pb2.CommentRequest.SerializeToString,
                response_deserializer=post__pb2.CommentResponse.FromString,
                _registered_method=True)
        self.ReplyComment = channel.unary_unary(
                '/posts.PostsService/ReplyComment',
                request_serializer=post__pb2.CommentCreateRequest.SerializeToString,
                response_deserializer=post__pb2.CommentResponse.FromString,
                _registered_method=True)
        self.GetReplies = channel.unary_unary(
                '/posts.PostsService/GetReplies',
                request_serializer=post__pb2.GetRepliesRequest.SerializeToString,
                response_deserializer=post__pb2.CommentListResponse.FromString,
                _registered_method=True)
        self.LikeComment = channel.unary_unary(
                '/posts.PostsService/LikeComment',
                request_serializer=post__pb2.CommentLikeRequest.SerializeToString,
                response_deserializer=post__pb2.CommentResponse.FromString,
                _registered_method=True)
        self.UnlikeComment = channel.unary_unary(
                '/posts.PostsService/UnlikeComment',
                request_serializer=post__pb2.CommentLikeRequest.SerializeToString,
                response_deserializer=post__pb2.CommentResponse.FromString,
                _registered_method=True)
        self.ReportComment = channel.unary_unary(
                '/posts.PostsService/ReportComment',
                request_serializer=post__pb2.ReportCommentRequest.SerializeToString,
                response_deserializer=post__pb2.ReportResponse.FromString,
                _registered_method=True)
        self.SharePost = channel.unary_unary(
                '/posts.PostsService/SharePost',
                request_serializer=post__pb2.SharePostRequest.SerializeToString,
                response_deserializer=post__pb2.PostShareResponse.FromString,
                _registered_method=True)
        self.GetSharedPosts = channel.unary_unary(
                '/posts.PostsService/GetSharedPosts',
                request_serializer=post__pb2.GetSharedPostsRequest.SerializeToString,
                response_deserializer=post__pb2.PostShareListResponse.FromString,
                _registered_method=True)
        self.DeleteSharedPost = channel.unary_unary(
                '/posts.PostsService/DeleteSharedPost',
                request_serializer=post__pb2.DeleteSharedPostRequest.SerializeToString,
                response_deserializer=post__pb2.GenericResponse.FromString,
                _registered_method=True)
        self.ReportPost = channel.unary_unary(
                '/posts.PostsService/ReportPost',
                request_serializer=post__pb2.ReportPostRequest.SerializeToString,
                response_deserializer=post__pb2.ReportResponse.FromString,
                _registered_method=True)
        self.ReportProperty = channel.unary_unary(
                '/posts.PostsService/ReportProperty',
                request_serializer=post__pb2.ReportPropertyRequest.SerializeToString,
                response_deserializer=post__pb2.ReportResponse.FromString,
                _registered_method=True)
        self.ReportUser = channel.unary_unary(
                '/posts.PostsService/ReportUser',
                request_serializer=post__pb2.ReportUserRequest.SerializeToString,
                response_deserializer=post__pb2.ReportResponse.FromString,
                _registered_method=True)
        self.GetMyReports = channel.unary_unary(
                '/posts.PostsService/GetMyReports',
                request_serializer=post__pb2.GetMyReportsRequest.SerializeToString,
                response_deserializer=post__pb2.ReportListResponse.FromString,
                _registered_method=True)
        self.GetReport = channel.unary_unary(
                '/posts.PostsService/GetReport',
                request_serializer=post__pb2.GetReportRequest.SerializeToString,
                response_deserializer=post__pb2.ReportResponse.FromString,
                _registered_method=True)
        self.GetReports = channel.unary_unary(
                '/posts.PostsService/GetReports',
                request_serializer=post__pb2.GetReportsRequest.SerializeToString,
                response_deserializer=post__pb2.ReportListResponse.FromString,
                _registered_method=True)
        self.UpdateReportStatus = channel.unary_unary(
                '/posts.PostsService/UpdateReportStatus',
                request_serializer=post__pb2.UpdateReportStatusRequest.SerializeToString,
                response_deserializer=post__pb2.ReportResponse.FromString,
                _registered_method=True)
        self.AssignReport = channel.unary_unary(
                '/posts.PostsService/AssignReport',
                request_serializer=post__pb2.AssignReportRequest.SerializeToString,
                response_deserializer=post__pb2.ReportResponse.FromString,
                _registered_method=True)
        self.GetReportsByEntity = channel.unary_unary(
                '/posts.PostsService/GetReportsByEntity',
                request_serializer=post__pb2.GetReportsByEntityRequest.SerializeToString,
                response_deserializer=post__pb2.ReportListResponse.FromString,
                _registered_method=True)
        self.GetReportStats = channel.unary_unary(
                '/posts.PostsService/GetReportStats',
                request_serializer=post__pb2.ReportStatsRequest.SerializeToString,
                response_deserializer=post__pb2.ReportStatsResponse.FromString,
                _registered_method=True)
        self.DeleteReport = channel.unary_unary(
                '/posts.PostsService/DeleteReport',
                request_serializer=post__pb2.GetReportRequest.SerializeToString,
                response_deserializer=post__pb2.GenericResponse.FromString,
                _registered_method=True)


class PostsServiceServicer(object):
    """---------------------------------------------------------------------------
    Service
    ---------------------------------------------------------------------------

    """

    def CreatePost(self, request, context):
        """Post operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPost(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdatePost(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeletePost(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPostsByUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMyPosts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPublicPosts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPropertyPosts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBuilderPosts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchPosts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TrendingPosts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PinPost(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnpinPost(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ArchivePost(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RestoreArchivedPost(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddPostMedia(self, request, context):
        """Media operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeletePostMedia(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LikePost(self, request, context):
        """Post like operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnlikePost(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPostLikes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckLikeStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateComment(self, request, context):
        """Comment operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateComment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteComment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetComments(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetComment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReplyComment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetReplies(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LikeComment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnlikeComment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportComment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SharePost(self, request, context):
        """Share operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSharedPosts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteSharedPost(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportPost(self, request, context):
        """Report operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportProperty(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMyReports(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetReport(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetReports(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateReportStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AssignReport(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetReportsByEntity(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetReportStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteReport(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PostsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreatePost': grpc.unary_unary_rpc_method_handler(
                    servicer.CreatePost,
                    request_deserializer=post__pb2.PostCreateRequest.FromString,
                    response_serializer=post__pb2.PostResponse.SerializeToString,
            ),
            'GetPost': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPost,
                    request_deserializer=post__pb2.PostRequest.FromString,
                    response_serializer=post__pb2.PostResponse.SerializeToString,
            ),
            'UpdatePost': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdatePost,
                    request_deserializer=post__pb2.PostUpdateRequest.FromString,
                    response_serializer=post__pb2.PostResponse.SerializeToString,
            ),
            'DeletePost': grpc.unary_unary_rpc_method_handler(
                    servicer.DeletePost,
                    request_deserializer=post__pb2.PostRequest.FromString,
                    response_serializer=post__pb2.GenericResponse.SerializeToString,
            ),
            'GetPostsByUser': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPostsByUser,
                    request_deserializer=post__pb2.GetPostsByUserRequest.FromString,
                    response_serializer=post__pb2.PostListResponse.SerializeToString,
            ),
            'GetMyPosts': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMyPosts,
                    request_deserializer=post__pb2.GetMyPostsRequest.FromString,
                    response_serializer=post__pb2.PostListResponse.SerializeToString,
            ),
            'GetPublicPosts': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPublicPosts,
                    request_deserializer=post__pb2.GetPublicPostsRequest.FromString,
                    response_serializer=post__pb2.PostListResponse.SerializeToString,
            ),
            'GetPropertyPosts': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPropertyPosts,
                    request_deserializer=post__pb2.GetPropertyPostsRequest.FromString,
                    response_serializer=post__pb2.PostListResponse.SerializeToString,
            ),
            'GetBuilderPosts': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBuilderPosts,
                    request_deserializer=post__pb2.GetBuilderPostsRequest.FromString,
                    response_serializer=post__pb2.PostListResponse.SerializeToString,
            ),
            'SearchPosts': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchPosts,
                    request_deserializer=post__pb2.SearchPostsRequest.FromString,
                    response_serializer=post__pb2.PostListResponse.SerializeToString,
            ),
            'TrendingPosts': grpc.unary_unary_rpc_method_handler(
                    servicer.TrendingPosts,
                    request_deserializer=post__pb2.TrendingPostsRequest.FromString,
                    response_serializer=post__pb2.PostListResponse.SerializeToString,
            ),
            'PinPost': grpc.unary_unary_rpc_method_handler(
                    servicer.PinPost,
                    request_deserializer=post__pb2.PostOwnerRequest.FromString,
                    response_serializer=post__pb2.PostResponse.SerializeToString,
            ),
            'UnpinPost': grpc.unary_unary_rpc_method_handler(
                    servicer.UnpinPost,
                    request_deserializer=post__pb2.PostOwnerRequest.FromString,
                    response_serializer=post__pb2.PostResponse.SerializeToString,
            ),
            'ArchivePost': grpc.unary_unary_rpc_method_handler(
                    servicer.ArchivePost,
                    request_deserializer=post__pb2.PostOwnerRequest.FromString,
                    response_serializer=post__pb2.PostResponse.SerializeToString,
            ),
            'RestoreArchivedPost': grpc.unary_unary_rpc_method_handler(
                    servicer.RestoreArchivedPost,
                    request_deserializer=post__pb2.PostOwnerRequest.FromString,
                    response_serializer=post__pb2.PostResponse.SerializeToString,
            ),
            'AddPostMedia': grpc.unary_unary_rpc_method_handler(
                    servicer.AddPostMedia,
                    request_deserializer=post__pb2.PostMediaRequest.FromString,
                    response_serializer=post__pb2.PostResponse.SerializeToString,
            ),
            'DeletePostMedia': grpc.unary_unary_rpc_method_handler(
                    servicer.DeletePostMedia,
                    request_deserializer=post__pb2.MediaIdRequest.FromString,
                    response_serializer=post__pb2.GenericResponse.SerializeToString,
            ),
            'LikePost': grpc.unary_unary_rpc_method_handler(
                    servicer.LikePost,
                    request_deserializer=post__pb2.LikeRequest.FromString,
                    response_serializer=post__pb2.PostResponse.SerializeToString,
            ),
            'UnlikePost': grpc.unary_unary_rpc_method_handler(
                    servicer.UnlikePost,
                    request_deserializer=post__pb2.LikeRequest.FromString,
                    response_serializer=post__pb2.PostResponse.SerializeToString,
            ),
            'GetPostLikes': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPostLikes,
                    request_deserializer=post__pb2.GetPostLikesRequest.FromString,
                    response_serializer=post__pb2.PostLikeListResponse.SerializeToString,
            ),
            'CheckLikeStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckLikeStatus,
                    request_deserializer=post__pb2.CheckLikeStatusRequest.FromString,
                    response_serializer=post__pb2.CheckLikeStatusResponse.SerializeToString,
            ),
            'CreateComment': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateComment,
                    request_deserializer=post__pb2.CommentCreateRequest.FromString,
                    response_serializer=post__pb2.CommentResponse.SerializeToString,
            ),
            'UpdateComment': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateComment,
                    request_deserializer=post__pb2.CommentUpdateRequest.FromString,
                    response_serializer=post__pb2.CommentResponse.SerializeToString,
            ),
            'DeleteComment': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteComment,
                    request_deserializer=post__pb2.CommentRequest.FromString,
                    response_serializer=post__pb2.GenericResponse.SerializeToString,
            ),
            'GetComments': grpc.unary_unary_rpc_method_handler(
                    servicer.GetComments,
                    request_deserializer=post__pb2.GetCommentsRequest.FromString,
                    response_serializer=post__pb2.CommentListResponse.SerializeToString,
            ),
            'GetComment': grpc.unary_unary_rpc_method_handler(
                    servicer.GetComment,
                    request_deserializer=post__pb2.CommentRequest.FromString,
                    response_serializer=post__pb2.CommentResponse.SerializeToString,
            ),
            'ReplyComment': grpc.unary_unary_rpc_method_handler(
                    servicer.ReplyComment,
                    request_deserializer=post__pb2.CommentCreateRequest.FromString,
                    response_serializer=post__pb2.CommentResponse.SerializeToString,
            ),
            'GetReplies': grpc.unary_unary_rpc_method_handler(
                    servicer.GetReplies,
                    request_deserializer=post__pb2.GetRepliesRequest.FromString,
                    response_serializer=post__pb2.CommentListResponse.SerializeToString,
            ),
            'LikeComment': grpc.unary_unary_rpc_method_handler(
                    servicer.LikeComment,
                    request_deserializer=post__pb2.CommentLikeRequest.FromString,
                    response_serializer=post__pb2.CommentResponse.SerializeToString,
            ),
            'UnlikeComment': grpc.unary_unary_rpc_method_handler(
                    servicer.UnlikeComment,
                    request_deserializer=post__pb2.CommentLikeRequest.FromString,
                    response_serializer=post__pb2.CommentResponse.SerializeToString,
            ),
            'ReportComment': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportComment,
                    request_deserializer=post__pb2.ReportCommentRequest.FromString,
                    response_serializer=post__pb2.ReportResponse.SerializeToString,
            ),
            'SharePost': grpc.unary_unary_rpc_method_handler(
                    servicer.SharePost,
                    request_deserializer=post__pb2.SharePostRequest.FromString,
                    response_serializer=post__pb2.PostShareResponse.SerializeToString,
            ),
            'GetSharedPosts': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSharedPosts,
                    request_deserializer=post__pb2.GetSharedPostsRequest.FromString,
                    response_serializer=post__pb2.PostShareListResponse.SerializeToString,
            ),
            'DeleteSharedPost': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteSharedPost,
                    request_deserializer=post__pb2.DeleteSharedPostRequest.FromString,
                    response_serializer=post__pb2.GenericResponse.SerializeToString,
            ),
            'ReportPost': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportPost,
                    request_deserializer=post__pb2.ReportPostRequest.FromString,
                    response_serializer=post__pb2.ReportResponse.SerializeToString,
            ),
            'ReportProperty': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportProperty,
                    request_deserializer=post__pb2.ReportPropertyRequest.FromString,
                    response_serializer=post__pb2.ReportResponse.SerializeToString,
            ),
            'ReportUser': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportUser,
                    request_deserializer=post__pb2.ReportUserRequest.FromString,
                    response_serializer=post__pb2.ReportResponse.SerializeToString,
            ),
            'GetMyReports': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMyReports,
                    request_deserializer=post__pb2.GetMyReportsRequest.FromString,
                    response_serializer=post__pb2.ReportListResponse.SerializeToString,
            ),
            'GetReport': grpc.unary_unary_rpc_method_handler(
                    servicer.GetReport,
                    request_deserializer=post__pb2.GetReportRequest.FromString,
                    response_serializer=post__pb2.ReportResponse.SerializeToString,
            ),
            'GetReports': grpc.unary_unary_rpc_method_handler(
                    servicer.GetReports,
                    request_deserializer=post__pb2.GetReportsRequest.FromString,
                    response_serializer=post__pb2.ReportListResponse.SerializeToString,
            ),
            'UpdateReportStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateReportStatus,
                    request_deserializer=post__pb2.UpdateReportStatusRequest.FromString,
                    response_serializer=post__pb2.ReportResponse.SerializeToString,
            ),
            'AssignReport': grpc.unary_unary_rpc_method_handler(
                    servicer.AssignReport,
                    request_deserializer=post__pb2.AssignReportRequest.FromString,
                    response_serializer=post__pb2.ReportResponse.SerializeToString,
            ),
            'GetReportsByEntity': grpc.unary_unary_rpc_method_handler(
                    servicer.GetReportsByEntity,
                    request_deserializer=post__pb2.GetReportsByEntityRequest.FromString,
                    response_serializer=post__pb2.ReportListResponse.SerializeToString,
            ),
            'GetReportStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetReportStats,
                    request_deserializer=post__pb2.ReportStatsRequest.FromString,
                    response_serializer=post__pb2.ReportStatsResponse.SerializeToString,
            ),
            'DeleteReport': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteReport,
                    request_deserializer=post__pb2.GetReportRequest.FromString,
                    response_serializer=post__pb2.GenericResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'posts.PostsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('posts.PostsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PostsService(object):
    """---------------------------------------------------------------------------
    Service
    ---------------------------------------------------------------------------

    """

    @staticmethod
    def CreatePost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/posts.PostsService/CreatePost',
            post__pb2.PostCreateRequest.SerializeToString,
            post__pb2.PostResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/posts.PostsService/GetPost',
            post__pb2.PostRequest.SerializeToString,
            post__pb2.PostResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdatePost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/posts.PostsService/UpdatePost',
            post__pb2.PostUpdateRequest.SerializeToString,
            post__pb2.PostResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeletePost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/posts.PostsService/DeletePost',
            post__pb2.PostRequest.SerializeToString,
            post__pb2.GenericResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPostsByUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/posts.PostsService/GetPostsByUser',
            post__pb2.GetPostsByUserRequest.SerializeToString,
            post__pb2.PostListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMyPosts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/posts.PostsService/GetMyPosts',
            post__pb2.GetMyPostsRequest.SerializeToString,
            post__pb2.PostListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPublicPosts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/posts.PostsService/GetPublicPosts',
            post__pb2.GetPublicPostsRequest.SerializeToString,
            post__pb2.PostListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPropertyPosts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/posts.PostsService/GetPropertyPosts',
            post__pb2.GetPropertyPostsRequest.SerializeToString,
            post__pb2.PostListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBuilderPosts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/posts.PostsService/GetBuilderPosts',
            post__pb2.GetBuilderPostsRequest.SerializeToString,
            post__pb2.PostListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchPosts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/posts.PostsService/SearchPosts',
            post__pb2.SearchPostsRequest.SerializeToString,
            post__pb2.PostListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TrendingPosts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/posts.PostsService/TrendingPosts',
            post__pb2.TrendingPostsRequest.SerializeToString,
            post__pb2.PostListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PinPost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/posts.PostsService/PinPost',
            post__pb2.PostOwnerRequest.SerializeToString,
            post__pb2.PostResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnpinPost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/posts.PostsService/UnpinPost',
            post__pb2.PostOwnerRequest.SerializeToString,
            post__pb2.PostResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ArchivePost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/posts.PostsService/ArchivePost',
            post__pb2.PostOwnerRequest.SerializeToString,
            post__pb2.PostResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RestoreArchivedPost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/posts.PostsService/RestoreArchivedPost',
            post__pb2.PostOwnerRequest.SerializeToString,
            post__pb2.PostResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddPostMedia(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/posts.PostsService/AddPostMedia',
            post__pb2.PostMediaRequest.SerializeToString,
            post__pb2.PostResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeletePostMedia(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/posts.PostsService/DeletePostMedia',
            post__pb2.MediaIdRequest.SerializeToString,
            post__pb2.GenericResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LikePost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/posts.PostsService/LikePost',
            post__pb2.LikeRequest.SerializeToString,
            post__pb2.PostResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnlikePost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/posts.PostsService/UnlikePost',
            post__pb2.LikeRequest.SerializeToString,
            post__pb2.PostResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPostLikes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/posts.PostsService/GetPostLikes',
            post__pb2.GetPostLikesRequest.SerializeToString,
            post__pb2.PostLikeListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckLikeStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/posts.PostsService/CheckLikeStatus',
            post__pb2.CheckLikeStatusRequest.SerializeToString,
            post__pb2.CheckLikeStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateComment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/posts.PostsService/CreateComment',
            post__pb2.CommentCreateRequest.SerializeToString,
            post__pb2.CommentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateComment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/posts.PostsService/UpdateComment',
            post__pb2.CommentUpdateRequest.SerializeToString,
            post__pb2.CommentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteComment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/posts.PostsService/DeleteComment',
            post__pb2.CommentRequest.SerializeToString,
            post__pb2.GenericResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetComments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/posts.PostsService/GetComments',
            post__pb2.GetCommentsRequest.SerializeToString,
            post__pb2.CommentListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetComment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/posts.PostsService/GetComment',
            post__pb2.CommentRequest.SerializeToString,
            post__pb2.CommentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReplyComment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/posts.PostsService/ReplyComment',
            post__pb2.CommentCreateRequest.SerializeToString,
            post__pb2.CommentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetReplies(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/posts.PostsService/GetReplies',
            post__pb2.GetRepliesRequest.SerializeToString,
            post__pb2.CommentListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LikeComment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/posts.PostsService/LikeComment',
            post__pb2.CommentLikeRequest.SerializeToString,
            post__pb2.CommentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnlikeComment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/posts.PostsService/UnlikeComment',
            post__pb2.CommentLikeRequest.SerializeToString,
            post__pb2.CommentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportComment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/posts.PostsService/ReportComment',
            post__pb2.ReportCommentRequest.SerializeToString,
            post__pb2.ReportResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SharePost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/posts.PostsService/SharePost',
            post__pb2.SharePostRequest.SerializeToString,
            post__pb2.PostShareResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSharedPosts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/posts.PostsService/GetSharedPosts',
            post__pb2.GetSharedPostsRequest.SerializeToString,
            post__pb2.PostShareListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteSharedPost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/posts.PostsService/DeleteSharedPost',
            post__pb2.DeleteSharedPostRequest.SerializeToString,
            post__pb2.GenericResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportPost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/posts.PostsService/ReportPost',
            post__pb2.ReportPostRequest.SerializeToString,
            post__pb2.ReportResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportProperty(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/posts.PostsService/ReportProperty',
            post__pb2.ReportPropertyRequest.SerializeToString,
            post__pb2.ReportResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/posts.PostsService/ReportUser',
            post__pb2.ReportUserRequest.SerializeToString,
            post__pb2.ReportResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMyReports(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/posts.PostsService/GetMyReports',
            post__pb2.GetMyReportsRequest.SerializeToString,
            post__pb2.ReportListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetReport(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/posts.PostsService/GetReport',
            post__pb2.GetReportRequest.SerializeToString,
            post__pb2.ReportResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetReports(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/posts.PostsService/GetReports',
            post__pb2.GetReportsRequest.SerializeToString,
            post__pb2.ReportListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateReportStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/posts.PostsService/UpdateReportStatus',
            post__pb2.UpdateReportStatusRequest.SerializeToString,
            post__pb2.ReportResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AssignReport(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/posts.PostsService/AssignReport',
            post__pb2.AssignReportRequest.SerializeToString,
            post__pb2.ReportResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetReportsByEntity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/posts.PostsService/GetReportsByEntity',
            post__pb2.GetReportsByEntityRequest.SerializeToString,
            post__pb2.ReportListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetReportStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/posts.PostsService/GetReportStats',
            post__pb2.ReportStatsRequest.SerializeToString,
            post__pb2.ReportStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteReport(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/posts.PostsService/DeleteReport',
            post__pb2.GetReportRequest.SerializeToString,
            post__pb2.GenericResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
